<?php

namespace Skim\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

	public function getNextCategory(User $user)
    {
    	return $this
        	->createQueryBuilder('u')
        	->orderBy('u.views', 'DESC')
        	->setFirstResult($user->getLastcat()-1)
        	->setMaxResults(1)
        	->getQuery()
        	->getSingleResult()
    	;
    }

    public function countAllCategories()
    {
        return $this
            ->createQueryBuilder('u')
            ->select('COUNT(u.id)')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    public function exists($category_id)
    {
        return $this
            ->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->where('c.id = :category')
            ->setMaxResults(1)
            ->setParameter('category', $category_id)
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

}
