<?php

namespace Skim\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Skim\MainBundle\Entity\User;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{

	public function getLastUrlOfUser(User $user)
	{
		return $this
			->createQueryBuilder('h')
			->where('h.user = :user')
			->orderBy('h.id', 'DESC')
			->setMaxResults(1)
			->setParameter('user', $user)
			->getQuery()
			->getSingleResult()
		;
	}

}
