<?php

namespace Skim\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository
{
	 public function getRandomUrlFromCategoryOnRating(Category $category, User $user)
    {
        return $this
            ->createQueryBuilder('u')
            ->leftJoin('u.history', 'h', 'WITH', 'h.user = :user')
            ->andWhere('u.category = :category')
            ->andwhere('h.url IS NULL')
            ->setFirstResult(rand(0,$this->countAllProducts($category, $user)-1))
            ->setMaxResults(1)
            ->setParameter('category', $category->getId())
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleResult()
        ;

    }

    public function countAllProducts(Category $category, User $user)
    {
        return $this
            ->createQueryBuilder('u')
            ->leftJoin('u.history', 'h', 'WITH', 'h.user = :user')
            ->select("COUNT(u.id)")
            ->andWhere('u.category = :category')
            ->andwhere('h.url IS NULL')
            ->setParameter('category', $category->getId())
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }

    public function getNewestUrlFromFollowing(User $user)
    {
        return $this
              ->createQueryBuilder('u')
              ->innerJoin('u.user', 'f')
              ->innerJoin('f.followers', 'ff', 'WITH', 'ff.follower = :user')
              ->leftJoin('u.history', 'h', 'WITH', 'h.user = :user')
              ->orderBy('u.id', 'DESC')
              ->setMaxResults(1)
              ->where('h.url IS NULL')
              ->setParameter('user', $user)
              ->getQuery()
              ->getSingleResult()
        ;
    }

    public function getBestUrlofCategory(Category $category)
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.category = :category')
            ->setMaxResults(1)
            ->setParameter('category', $category)
            ->getQuery()
            ->getSingleResult()
        ;
    }
}