<?php

namespace Skim\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Skim\MainBundle\Entity\Category;

/**
 * UrlScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlScoreRepository extends EntityRepository
{

	public function findScoreOfObjectByCategory($object, Category $category)
	{
		return $this
			->createQueryBuilder('u')
			->select('COUNT(u.id)')
			->where('u.url = :url')
			->andwhere('u.category = :category')
			->setMaxResults(1)
			->setParameter('url', $object)
			->setParameter('category', $category)
			->getQuery()
			->getSingleScalarResult()
		;
	}

	public function getScoreByCategory(Category $category, $url)
	{
		return $this
			->createQueryBuilder('u')
			->where('u.url = :url')
			->andwhere('u.category = :category')
			->setMaxResults(1)
			->setParameter('url', $url)
			->setParameter('category', $category)
			->getQuery()
			->getSingleResult()
		;
	}

	public function getHighestScoreOfObject($object)
	{
		return $this
			->createQueryBuilder('u')
			->where('u.url = :url')
			->orderby('u.percentage', 'DESC')
			->setMaxResults(1)
			->setParameter('url', $object)
			->getQuery()
			->getSingleResult()
		;
	}

}
